---
- hosts: all_server
  remote_user: root
  roles:
    - role: all
- hosts: install_master
  remote_user: root
  roles:
    - role: master
- hosts: install_node
  remote_user: root
  roles:
    - role: node
