- name: copy etcd
  template: src=etcd.j2 dest=/usr/local/kubernetes/cfg/etcd
- name: copy etcd-service
  template: src=etcd.service.j2 dest=/lib/systemd/system/etcd.service mode=0755
- name: start etcd
  service: name=etcd state=restarted enabled=yes
