- name: copy etcd
  unarchive: src={{ etcd_version }}.tar.gz dest=/home copy=yes
- name: bin etcd
  copy: src=/home/{{ etcd_version }}/etcd dest=/usr/local/bin/etcd mode=0755
- name: bin etcdctl
  copy: src=/home/{{ etcd_version }}/etcdctl dest=/usr/local/bin/etcdctl mode=0755
- name: kubernetes etcd
  copy: src=/home/{{ etcd_version }}/etcd dest=/usr/local/kubernetes/bin/etcd mode=0755
- name: kubernetes etcdctl
  copy: src=/home/{{ etcd_version }}/etcdctl dest=/usr/local/kubernetes/bin/etcdctl mode=0755
- name: rm -rf linux-amd64
  command: rm -rf /home/{{ etcd_version }}
