- name: update time 同步阿里云的时间服务器。
  shell: ntpdate ntp1.aliyun.com && hwclock --systohc
- name: update ntpdate daemon reload
  systemd:
    daemon_reload: yes
#- name: start
#  service: name=ntpdate state=started enabled=yes
