- name: copy kube-proxy
  template: src=kube-proxy.j2 dest=/usr/local/kubernetes/cfg/kube-proxy
- name: copy kube-proxy.service
  template: src=kube-proxy.service.j2 dest=/lib/systemd/system/kube-proxy.service mode=0755
