- name: copy apiserver
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
- name: update haproxy daemon reload
  systemd:
    daemon_reload: yes
- name: start haproxy
  service: name=haproxy state=restarted enabled=yes
