- name: copy kube-scheduler
  template: src=kube-scheduler.j2 dest=/usr/local/kubernetes/cfg/kube-scheduler
- name: copy kube-scheduler-service
  template: src=kube-scheduler.service.j2 dest=/lib/systemd/system/kube-scheduler.service mode=0755
